# Generated by Django 2.1.4 on 2019-12-17 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='audiobook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audiobooks.Audiobook'),
        ),
    ]
