# Generated by Django 3.0 on 2019-12-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0002_review_audiobook'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
